theme: jekyll-theme-slate
title: Workshop Documenting Research Practices in DH
description: Documenting Research Practices in DH Workshop, DH Benelux 11 September 2019
baseurl: /DHBenelux_Workshop_Documenting_Research_Practices
